"""empty message

Revision ID: 4410b1a9ac77
Revises: 941ebabf02a9
Create Date: 2021-08-25 17:06:44.901077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4410b1a9ac77'
down_revision = '941ebabf02a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('reward_name', sa.String(length=255), nullable=False),
    sa.Column('reward_detail', sa.String(length=255), nullable=True),
    sa.Column('reward_reason', sa.String(length=500), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rewards')
    # ### end Alembic commands ###
